(load "grid-class.ss")
(load "grid-draw.ss")
(load "grid-make.ss")
(load "grid-queue.ss")
(load "grid-stack.ss")
(load "grid-new.ss")
(load "grid-RTA.ss")

(define num-col-row 30)
(define pause-num 900000)
(define size (floor (/ 700 num-col-row)))
(define obstacle-density 30)
(define grid0 (make-grid num-col-row))
(draw-obstacles grid0)
(define grid (convert-grid grid0))
(create-instance search grid0)