(define num-col-row 30)
(define pause-num 100)
(define size (floor (/ 700 num-col-row)))
(define obstacle-density 20)
(load "grid-class.ss")
(load "grid-draw.ss")
(load "grid-make.ss")

(define grid0 (make-grid num-col-row))
(draw-obstacles grid0)
(define grid (convert-grid grid0))
(load "grid-new.ss")
(load "grid-BNB.ss")
(set-goal grid)
(set-start grid)
(draw-start)
(draw-goal)
(draw-robot)
(show canvas)
(search grid 20000)